server:
  port: 9090
  jsp-servlet:
    init-parameters:
      development: true
  context-path: testfor4
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver


  mvc:
    view:
      prefix: /
      suffix: .jsp


mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: com/baizhi/dao/*Mapper.xml


